# Generated by Django 5.2.1 on 2025-05-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0003_profile_sql_table_delete_profile_sql'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_sqll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME_FIELD', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Profile_sql_table',
        ),
    ]
