# Generated by Django 5.2.1 on 2025-05-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0004_profile_sqll_delete_profile_sql_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_sqll',
            old_name='USERNAME_FIELD',
            new_name='username',
        ),
    ]
